Run started:2025-06-19 00:15:42.675138

Test results:
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/authlib/oauth1/rfc5849/client_auth.py:150:47
149	        if body and headers.get("Content-Type") != CONTENT_TYPE_FORM_URLENCODED:
150	            oauth_body_hash = base64.b64encode(hashlib.sha1(body).digest())
151	            oauth_params.append(("oauth_body_hash", oauth_body_hash.decode("utf-8")))

--------------------------------------------------
>> Issue: [B613:trojansource] A Python source file contains bidirectional control characters ('\u202e').
   Severity: High   Confidence: Medium
   CWE: CWE-838 (https://cwe.mitre.org/data/definitions/838.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b613_trojansource.html
   Location: ./venv/lib/python3.12/site-packages/bandit/plugins/trojansource.py:22:36
21	     3  	access_level = "user"
22	     4	    if access_level != 'none‮⁦': # Check if admin ⁩⁦' and access_level != 'user
23	     5	        print("You are an admin.\n")

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./venv/lib/python3.12/site-packages/click/_termui_impl.py:429:8
428	        [cmd_absolute],
429	        shell=True,
430	        stdin=subprocess.PIPE,
431	        env=env,
432	        errors="replace",
433	        text=True,
434	    )
435	    assert c.stdin is not None
436	    try:
437	        for text in generator:

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./venv/lib/python3.12/site-packages/click/_termui_impl.py:552:16
551	        try:
552	            c = subprocess.Popen(f'{editor} "{filename}"', env=environ, shell=True)
553	            exit_code = c.wait()

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/cryptography/x509/extensions.py:72:11
71	
72	    return hashlib.sha1(data).digest()
73	

--------------------------------------------------
>> Issue: [B613:trojansource] A Python source file contains bidirectional control characters ('\u200f').
   Severity: High   Confidence: Medium
   CWE: CWE-838 (https://cwe.mitre.org/data/definitions/838.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b613_trojansource.html
   Location: ./venv/lib/python3.12/site-packages/django/conf/locale/ar/formats.py:10:23
9	MONTH_DAY_FORMAT = "j F"
10	SHORT_DATE_FORMAT = "d‏/m‏/Y"
11	# SHORT_DATETIME_FORMAT =

--------------------------------------------------
>> Issue: [B613:trojansource] A Python source file contains bidirectional control characters ('\u200f').
   Severity: High   Confidence: Medium
   CWE: CWE-838 (https://cwe.mitre.org/data/definitions/838.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b613_trojansource.html
   Location: ./venv/lib/python3.12/site-packages/django/conf/locale/ckb/formats.py:11:32
10	SHORT_DATE_FORMAT = "Y/n/j"
11	SHORT_DATETIME_FORMAT = "Y/n/j،‏ G:i"
12	FIRST_DAY_OF_WEEK = 6

--------------------------------------------------
>> Issue: [B613:trojansource] A Python source file contains bidirectional control characters ('\u200f').
   Severity: High   Confidence: Medium
   CWE: CWE-838 (https://cwe.mitre.org/data/definitions/838.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b613_trojansource.html
   Location: ./venv/lib/python3.12/site-packages/django/conf/locale/fa/formats.py:11:32
10	SHORT_DATE_FORMAT = "Y/n/j"
11	SHORT_DATETIME_FORMAT = "Y/n/j،‏ G:i"
12	FIRST_DAY_OF_WEEK = 6

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:658:15
657	        self._check_encode_args(password, salt)
658	        hash = hashlib.md5((salt + password).encode()).hexdigest()
659	        return "%s$%s$%s" % (self.algorithm, salt, hash)

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/django/db/backends/sqlite3/_functions.py:401:11
400	        return None
401	    return md5(text.encode()).hexdigest()
402	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/django/db/backends/sqlite3/_functions.py:447:11
446	        return None
447	    return sha1(text.encode()).hexdigest()
448	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/django/template/loaders/cached.py:96:15
95	    def generate_hash(self, values):
96	        return hashlib.sha1("|".join(values).encode()).hexdigest()
97	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/httpx/_auth.py:309:15
308	
309	        return hashlib.sha1(s).hexdigest()[:16].encode()
310	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/jinja2/bccache.py:156:15
155	        """Returns the unique hash key for this template name."""
156	        hash = sha1(name.encode("utf-8"))
157	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/jinja2/bccache.py:165:15
164	        """Returns a checksum for the source."""
165	        return sha1(source.encode("utf-8")).hexdigest()
166	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/jinja2/loaders.py:661:25
660	    def get_template_key(name: str) -> str:
661	        return "tmpl_" + sha1(name.encode("utf-8")).hexdigest()
662	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/joblib/test/test_hashing.py:228:15
227	    def md5_hash(x):
228	        return hashlib.md5(memoryview(x)).hexdigest()
229	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/nltk/downloader.py:2214:17
2213	def _md5_hexdigest(fp):
2214	    md5_digest = md5()
2215	    while True:

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./venv/lib/python3.12/site-packages/nltk/sem/boxer.py:271:16
270	            p = subprocess.Popen(
271	                cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True
272	            )
273	        stdout, stderr = p.communicate()
274	

--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b605_start_process_with_a_shell.html
   Location: ./venv/lib/python3.12/site-packages/pbr/testr_command.py:143:8
142	        os.system("coverage combine")
143	        os.system("coverage html -d ./cover %s" % self.omit)
144	        os.system("coverage xml -o ./cover/coverage.xml %s" % self.omit)

--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b605_start_process_with_a_shell.html
   Location: ./venv/lib/python3.12/site-packages/pbr/testr_command.py:144:8
143	        os.system("coverage html -d ./cover %s" % self.omit)
144	        os.system("coverage xml -o ./cover/coverage.xml %s" % self.omit)
145	

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./venv/lib/python3.12/site-packages/pip/_internal/commands/configuration.py:239:12
238	        try:
239	            subprocess.check_call(f'{editor} "{fname}"', shell=True)
240	        except FileNotFoundError as e:

--------------------------------------------------
>> Issue: [B411:blacklist] Using xmlrpc.client to parse untrusted XML data is known to be vulnerable to XML attacks. Use defusedxml.xmlrpc.monkey_patch() function to monkey-patch xmlrpclib and mitigate XML vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/blacklists/blacklist_imports.html#b411-import-xmlrpclib
   Location: ./venv/lib/python3.12/site-packages/pip/_internal/commands/search.py:5:0
4	import textwrap
5	import xmlrpc.client
6	from collections import OrderedDict

--------------------------------------------------
>> Issue: [B411:blacklist] Using xmlrpc.client to parse untrusted XML data is known to be vulnerable to XML attacks. Use defusedxml.xmlrpc.monkey_patch() function to monkey-patch xmlrpclib and mitigate XML vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/blacklists/blacklist_imports.html#b411-import-xmlrpclib
   Location: ./venv/lib/python3.12/site-packages/pip/_internal/network/xmlrpc.py:6:0
5	import urllib.parse
6	import xmlrpc.client
7	from typing import TYPE_CHECKING, Tuple

--------------------------------------------------
>> Issue: [B411:blacklist] Using _HostType to parse untrusted XML data is known to be vulnerable to XML attacks. Use defusedxml.xmlrpc.monkey_patch() function to monkey-patch xmlrpclib and mitigate XML vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/blacklists/blacklist_imports.html#b411-import-xmlrpclib
   Location: ./venv/lib/python3.12/site-packages/pip/_internal/network/xmlrpc.py:14:4
13	if TYPE_CHECKING:
14	    from xmlrpc.client import _HostType, _Marshallable
15	

--------------------------------------------------
>> Issue: [B411:blacklist] Using xmlrpclib to parse untrusted XML data is known to be vulnerable to XML attacks. Use defusedxml.xmlrpc.monkey_patch() function to monkey-patch xmlrpclib and mitigate XML vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/blacklists/blacklist_imports.html#b411-import-xmlrpclib
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/distlib/compat.py:42:4
41	    import httplib
42	    import xmlrpclib
43	    import Queue as queue

--------------------------------------------------
>> Issue: [B411:blacklist] Using xmlrpc.client to parse untrusted XML data is known to be vulnerable to XML attacks. Use defusedxml.xmlrpc.monkey_patch() function to monkey-patch xmlrpclib and mitigate XML vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/blacklists/blacklist_imports.html#b411-import-xmlrpclib
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/distlib/compat.py:81:4
80	    import urllib.request as urllib2
81	    import xmlrpc.client as xmlrpclib
82	    import queue

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/distlib/database.py:1032:19
1031	                f.close()
1032	            return hashlib.md5(content).hexdigest()
1033	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/distlib/index.py:269:21
268	            file_data = f.read()
269	        md5_digest = hashlib.md5(file_data).hexdigest()
270	        sha256_digest = hashlib.sha256(file_data).hexdigest()

--------------------------------------------------
>> Issue: [B202:tarfile_unsafe_members] tarfile.extractall used without any validation. Please check and discard dangerous members.
   Severity: High   Confidence: High
   CWE: CWE-22 (https://cwe.mitre.org/data/definitions/22.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b202_tarfile_unsafe_members.html
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/distlib/util.py:1310:8
1309	
1310	        archive.extractall(dest_dir)
1311	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/requests/auth.py:148:23
147	                    x = x.encode("utf-8")
148	                return hashlib.md5(x).hexdigest()
149	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/requests/auth.py:156:23
155	                    x = x.encode("utf-8")
156	                return hashlib.sha1(x).hexdigest()
157	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/pip/_vendor/requests/auth.py:205:17
204	
205	        cnonce = hashlib.sha1(s).hexdigest()[:16]
206	        if _algorithm == "MD5-SESS":

--------------------------------------------------
>> Issue: [B202:tarfile_unsafe_members] tarfile.extractall used without any validation. Please check and discard dangerous members.
   Severity: High   Confidence: High
   CWE: CWE-22 (https://cwe.mitre.org/data/definitions/22.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b202_tarfile_unsafe_members.html
   Location: ./venv/lib/python3.12/site-packages/pygments/lexers/_php_builtins.py:3301:12
3300	        with tarfile.open(download[0]) as tar:
3301	            tar.extractall()
3302	        yield from glob.glob(f"{PHP_MANUAL_DIR}{PHP_REFERENCE_GLOB}")

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/requests/auth.py:148:23
147	                    x = x.encode("utf-8")
148	                return hashlib.md5(x).hexdigest()
149	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/requests/auth.py:156:23
155	                    x = x.encode("utf-8")
156	                return hashlib.sha1(x).hexdigest()
157	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/requests/auth.py:205:17
204	
205	        cnonce = hashlib.sha1(s).hexdigest()[:16]
206	        if _algorithm == "MD5-SESS":

--------------------------------------------------
>> Issue: [B701:jinja2_autoescape_false] By default, jinja2 sets autoescape to False. Consider using autoescape=True or use the select_autoescape function to mitigate XSS vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-94 (https://cwe.mitre.org/data/definitions/94.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b701_jinja2_autoescape_false.html
   Location: ./venv/lib/python3.12/site-packages/safety/alerts/utils.py:128:10
127	    p = Path(__file__).parent / 'templates'
128	    env = jinja2.Environment(loader=jinja2.FileSystemLoader(Path(p)))
129	    template = env.get_template('pr.jinja2')

--------------------------------------------------
>> Issue: [B701:jinja2_autoescape_false] By default, jinja2 sets autoescape to False. Consider using autoescape=True or use the select_autoescape function to mitigate XSS vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-94 (https://cwe.mitre.org/data/definitions/94.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b701_jinja2_autoescape_false.html
   Location: ./venv/lib/python3.12/site-packages/safety/alerts/utils.py:164:10
163	    p = Path(__file__).parent / 'templates'
164	    env = jinja2.Environment(loader=jinja2.FileSystemLoader(Path(p)))
165	    template = env.get_template('issue.jinja2')

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/safety/alerts/utils.py:209:11
208	    """
209	    return hashlib.sha1(b"blob " + str(len(raw_contents)).encode('ascii') + b"\0" + raw_contents).hexdigest()
210	

--------------------------------------------------
>> Issue: [B701:jinja2_autoescape_false] By default, jinja2 sets autoescape to False. Consider using autoescape=True or use the select_autoescape function to mitigate XSS vulnerabilities.
   Severity: High   Confidence: High
   CWE: CWE-94 (https://cwe.mitre.org/data/definitions/94.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b701_jinja2_autoescape_false.html
   Location: ./venv/lib/python3.12/site-packages/safety/output_utils.py:1251:10
1250	    file_loader = PackageLoader('safety', 'templates')
1251	    env = Environment(loader=file_loader)
1252	    template = env.get_template(template)

--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b605_start_process_with_a_shell.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/_distutils/command/bdist_rpm.py:357:14
356	
357	        out = os.popen(q_cmd)
358	        try:

--------------------------------------------------
>> Issue: [B103:set_bad_file_permissions] Chmod setting a permissive mask 0o777 on file (exe).
   Severity: High   Confidence: High
   CWE: CWE-732 (https://cwe.mitre.org/data/definitions/732.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b103_set_bad_file_permissions.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/_distutils/tests/test_spawn.py:32:8
31	
32	        os.chmod(exe, 0o777)
33	        with pytest.raises(DistutilsExecError):

--------------------------------------------------
>> Issue: [B103:set_bad_file_permissions] Chmod setting a permissive mask 0o777 on file (exe).
   Severity: High   Confidence: High
   CWE: CWE-732 (https://cwe.mitre.org/data/definitions/732.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b103_set_bad_file_permissions.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/_distutils/tests/test_spawn.py:44:8
43	
44	        os.chmod(exe, 0o777)
45	        spawn([exe])  # should work without any error

--------------------------------------------------
>> Issue: [B202:tarfile_unsafe_members] tarfile.extractall used without any validation. Please check and discard dangerous members.
   Severity: High   Confidence: High
   CWE: CWE-22 (https://cwe.mitre.org/data/definitions/22.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b202_tarfile_unsafe_members.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/_vendor/jaraco/context.py:65:12
64	        with tarfile.open(fileobj=req, mode='r|*') as tf:
65	            tf.extractall(path=target_dir, filter=strip_first_component)
66	        yield target_dir

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/tests/environment.py:77:15
76	            stderr=_PIPE,
77	            shell=shell,
78	            env=env,
79	            encoding="utf-8",
80	        )
81	
82	        if isinstance(data_stream, tuple):
83	            data_stream = slice(*data_stream)
84	        data = proc.communicate()[data_stream]
85	    except OSError:

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b324_hashlib.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/tests/integration/test_pip_install_sdist.py:190:11
189	
190	    assert md5(data).hexdigest() == md5_digest
191	

--------------------------------------------------
>> Issue: [B103:set_bad_file_permissions] Chmod setting a permissive mask 0o777 on file (runsh).
   Severity: High   Confidence: High
   CWE: CWE-732 (https://cwe.mitre.org/data/definitions/732.html)
   More Info: https://bandit.readthedocs.io/en/1.8.5/plugins/b103_set_bad_file_permissions.html
   Location: ./venv/lib/python3.12/site-packages/setuptools/tests/test_wheel.py:626:12
625	            runsh = pathlib.Path(source_dir) / "script.sh"
626	            os.chmod(runsh, 0o777)
627	            subprocess.check_call(

--------------------------------------------------

Code scanned:
	Total lines of code: 884783
	Total lines skipped (#nosec): 3
	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 11

Run metrics:
	Total issues (by severity):
		Undefined: 0
		Low: 5973
		Medium: 384
		High: 48
	Total issues (by confidence):
		Undefined: 0
		Low: 29
		Medium: 156
		High: 6220
Files skipped (0):
